### ISSUE TITLE
index out of bounds errors

### ISSUE THREAD

**Issue by naturallymitchell** [jazz-lang/JazzLight#5]
```
root@server:~/JazzLight# jazz-vm/target/debug/jazzvm examples/file.j 
thread 'main' panicked at 'index out of bounds: the len is 148 but the index is 148', /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/slice/mod.rs:2681:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
root@server:~/JazzLight# jazz-vm/target/debug/jazzvm factorial.j 
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/929b48ec98aaff2239257574b5897f419cec2647/src/libcore/slice/mod.rs:2681:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by playXE** [comment]
Hmm, before updating VM I tested compiler and VM on windows. I will look at that error

**Comment by playXE** [comment]
I found a problem there. when you calling `fac(x - 1)` inside of `fac` function not yet defined in a global context so compiler inserts "empty" global and then after `fac` function compiled loading global with index `1`.

**Comment by playXE** [comment]
@naturallymitchell this bug now fixed
